### ISSUE TITLE
Pinned tab reordering optional

### ISSUE THREAD

**Issue by vaderf** [coolsoft-ita/autopintab#12]
Hello @nicorac,

First, thank you very much for having developed and maintaining this very useful add-on.

As mentioned in the change log, the latest version of the add-on reorders pinned tab following the pattern order in the pattern list. While I understand this feature can be useful, is there a way to make it optional? In other word, I would like to keep the old behavior of adding the recognized tab at the rightmost position.

Thank you,

Fred

**Comment by nicorac** [comment]
Well, I haven't thought about a "fallback" to the previous behavior.
It shouldn't be so hard to add a checkbox to enable/disable the new behavior...

Meanwhile, could you please help me understand what's your specific use-case that requires it?

**Comment by vaderf** [comment]
Thank you for giving some thoughts to this. 

When using tabs, I have roughly 3 groups:
* Tabs that are forever pinned (e.g., OneTab, Twitter, news).
* Tabs that are pinned for few weeks or month (e.g., music on YouTube, specific job tabs).
* Tabs that are pinned for few days (e.g., Jupyter notebooks for which I actually use AutoPinTab).

There are usually pinned in that order. I could use AutoPinTab to pin and order them this way but there are some behaviors that I would like to avoid: with Twitter or the news website, I only want the feed to be pinned, not every tab I will open which will clutter the pin area quickly. While these particular cases could probably be fixed with regex, this won't be possible for YouTube tabs.

Hope this is clear.

**Comment by DRSAgile** [comment]
> 
> 
> Well, I haven't thought about a "fallback" to the previous behavior. It shouldn't be so hard to add a checkbox to enable/disable the new behavior...
> 
> Meanwhile, could you please help me understand what's your specific use-case that requires it?

First of all, thanks for the extension.

My example is a bit different but still:

In the last few months, the newly pinned tabs get added to the beginning of the pinned tabs, not to the right as before.

I have a YouTube subscriptions tab (MANUALLY) pinned as the very first, it is on the left of the tabs area in the browser. When I click on a video instead of putting the new pinned tab to the right of my main pinned tab, it puts it as the very first pinned tab, thus always moving my main pinned tab to the right.

Is it possible to make a toggle in options to fix this or something?

Thanks in advance.

**Comment by nicorac** [comment]
An option to enable/disable tab reordering has been added to version 1.3.2

**Comment by DRSAgile** [comment]
Thanks.

I have tried the 1.3.2 version but when I load my pre-saved list of the URLs to pin it does not work. I have restarted the browser, installed and then re-installed the extension, still the same result. Older versions still work though.

**Comment by nicorac** [comment]
Do you have any errors in browser console (CTRL+SHIFT+I)?

**Comment by DRSAgile** [comment]
Nothing in particular: neither on the page where I click on a link to be pinned later nor on the page that should have been pinned.

Switching "Reorder ..." tumbler does not make it work in any mode, too.

The Options page keeps the URLs just fine during all this, nothing is lost or anything.

**Comment by nicorac** [comment]
Can't reproduce the same behavior, sorry...

Could you please post your saved `autopintab-settings.json` file content here?
(feel free to remove any "sensitive" URL by carefully replacing `pattern: "private.web.site"` elements content with something else like `xxx.yyy.zzz`, **without** changing file structure).

**Comment by DRSAgile** [comment]
There is nothing sensitive about the settings so I will post the exact full data below. The structure seems fine and I now re-exported the imported settings from the 1.3.2 version and got the very same file so nothing gets corrupted on this stage. 

It looks like setting "extensions.webextensions.keepStorageOnUninstall" to "true" in Firefox somehow helps the 1.3.2 version to work through when upgraded from the 1.2.1 version. But it also makes something else wrong since I install the extension sometimes it shows me an absolutely empty "Options" tab and then the extension disappears from the list of installed as if I have never installed it. Then I install it a second time and it stays -- however the version 1.2.1 works and 1.3.2 does not.

(By default, including now, I am keeping  "extensions.webextensions.keepStorageOnUninstall" false not to mess with anything in terms of extensions if they are not processing having their old storage there upon installation properly.)

But I am doing all of this in the Developer Edition of Firefox, meaning beta, so maybe those storage-related glitches are actually browser-related?

`{
 "patterns": [
  {
   "pattern": "&feature=pin-this-tab",
   "isRegex": true,
   "enabled": true
  },
  {
   "pattern": "&feature=em-uploademail",
   "isRegex": true,
   "enabled": true
  },
  {
   "pattern": "&feature=em-lbcastemail",
   "isRegex": true,
   "enabled": true
  },
  {
   "pattern": "&feature=em-lsp",
   "isRegex": true,
   "enabled": true
  },
  {
   "pattern": "&feature=push-u-sub",
   "isRegex": true,
   "enabled": true
  },
  {
   "pattern": "&feature=push-lbss",
   "isRegex": true,
   "enabled": true
  },
  {
   "pattern": "youtube\\.com.*&lc=",
   "isRegex": true,
   "enabled": false
  },
  {
   "pattern": "moz-extension:\\/\\/33fcf49c-74da-4efd-8e5b-a003ecca752c\\/",
   "isRegex": true,
   "enabled": true
  },
  {
   "pattern": "moz-extension:\\/\\/2a28ad11-9122-461a-83e0-170655e08b75\\/reader\\.html",
   "isRegex": true,
   "enabled": true
  }
 ]
}`
